name: 'YellowElectricWarrior '
favicon: null
layout_spectrum: 0.5408218805678189
typography_spectrum: 0.9634696210268885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24604747095145285
  lightness: 0.23491877014748752
  saturation: 0.47799785854294896
  rhythmicContrast: 0.3474058243446052
purpose: []
